{
  # RedPajama

  # parallelism settings
  "pipe-parallel-size": 1,
  "model-parallel-size": 1,

  # model settings
  "num-layers": 24,
  "hidden-size": 2048,
  "num-attention-heads": 16,
  "seq-length": 4096,
  "max-position-embeddings": 4096,

  # architecture design
  "norm": "layernorm",
  "pos-emb": "rotary",
  "rotary_pct": 0.25,
  "activation": "gelu",
  "no-weight-tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # fused ops
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,
  "attention-config": [[["flash"], 24]],

  # optimizer settings
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.4e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 3.4e-5,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  # batch / data settings
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 2,
  "eval_batch_size": 4,
  "data-impl": "mmap",

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  # misc. training settings
  # 66k iters ~= 550B tokens at bs=8.3M
  # 120k iters = 1T tokens at bs=8.3M
  # 240k iters = 1T tokens at bs=4.1M
  # 180k iters = 1.5T tokens at bs=8.3M
  # 360k iters = 3T tokens at bs=4.1M
  "train-iters": 100,
  "lr-decay-iters": 100,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 10,
  # 1 more than checkpoint-factor to avoid skipping evals if `evaluate` fails
  "eval-interval": 11,
  "eval-iters": 10,
  # early logarithmic save iters:
  # "extra-save-iters": [0,1,2,4,8,16,32,64,128,256,512,1024,2048],
  "eval_tasks": ["lambada_openai", "piqa", "sciq"],

  # checkpoint settings
  "save": "/fsx/ckpts/1b_tok=neox_data=test-s3-upload",
  "load": "/fsx/ckpts/1b_tok=neox_data=test-s3-upload",

  # s3 settings
  "s3_path": "s3://stability-checkpoints-east",
  "s3_region": "us-east-1",

  # data settings
  # (AWS East paths)
  "train-data-paths": ["/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document", "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/github/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document"],
  "train-data-weights": [2.5, 4.5, 15.0, 17.816091954022987, 21.408045977011493, 20.617816091954023, 18.75, 21.408045977011493, 4.5, 2.0, 4.5],
  "valid-data-paths": ["/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document", "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/github/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document"],
  "valid-data-weights": [2.5, 4.5, 15.0, 17.816091954022987, 21.408045977011493, 20.617816091954023, 18.75, 21.408045977011493, 4.5, 2.0, 4.5],
  "test-data-paths": ["/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document", "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/github/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",  "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document"],
  "test-data-weights": [2.5, 4.5, 15.0, 17.816091954022987, 21.408045977011493, 20.617816091954023, 18.75, 21.408045977011493, 4.5, 2.0, 4.5],

  # tokenizer settings
  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/fsx/pile/20B_tokenizer.json",

  # log settings
  "log-interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  "use_wandb": true,
  "wandb_host": "https://stability.wandb.io",
  "wandb_team": "stability-llm",
  "wandb_project": "stable-lm",
  "wandb_group": "1B",
  "wandb_name": "1B.neox.redpajama",
  # "wandb_id": "",
  # "wandb_resume": "must",

  # multi-node launcher
  "launcher": "slurm",
  "deepspeed_slurm": true
}