{
  # RedPajama

  # parallelism settings
  "pipe-parallel-size": 1,
  "model-parallel-size": 1,

  # model settings
  "num-layers": 24,
  "hidden-size": 2048,
  "num-attention-heads": 16,
  "seq-length": 4096,
  "max-position-embeddings": 4096,

  # architecture design
  "norm": "layernorm",
  "pos-emb": "rotary",
  "rotary_pct": 0.25,
  "activation": "gelu",
  "no-weight-tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # fused ops
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,
  "attention-config": [[["flash"], 24]],

  # optimizer settings
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.4e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 3.4e-5,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  # batch / data settings
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 2,
  "eval_batch_size": 4,
  "data-impl": "mmap",

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  # misc. training settings
  # 66k iters ~= 550B tokens at bs=8.3M
  # 120k iters = 1T tokens at bs=8.3M
  # 240k iters = 1T tokens at bs=4.1M
  # 180k iters = 1.5T tokens at bs=8.3M
  # 360k iters = 3T tokens at bs=4.1M
  "train-iters": 360000,
  "lr-decay-iters": 360000,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 1000,
  # 1 more than checkpoint-factor to avoid skipping evals if `evaluate` fails
  "eval-interval": 1001,
  "eval-iters": 10,
  # early logarithmic save iters:
  # "extra-save-iters": [0,1,2,4,8,16,32,64,128,256,512,1024,2048],
  "eval_tasks": ["lambada_openai", "piqa", "sciq"],

  # checkpoint settings
  "save": "/fsx/ckpts/1b_tok=neox_data=hq",
  "load": "/fsx/ckpts/1b_tok=neox_data=hq",

  # data settings
  # (AWS East paths)
  "train-data-paths": [
    "/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document",
    "/fsx/pilev2/merged/the_stack/the_stack",
    "/fsx/pilev2/merged/pubmed_fix/pubmed_fix",
    "/fsx/pilev2/merged/soda/soda",
    "/fsx/pilev2/merged/uspto/uspto",
    "/fsx/pilev2/merged/pile_of_law/pile_of_law",
    "/fsx/pilev2/merged/free_law_fix/free_law_fix",
    "/fsx/pilev2/merged/amps_fix/amps_fix",
    "/fsx/pilev2/merged/dm_math_fix/dm_math_fix"
  ],
  "train-data-weights": [
    2.070006806279234,
    1.9171640675752055,
    6.43783843754923,
    4.586037603579489,
    6.954359988235985,
    8.001256232179825,
    8.49256192461039,
    11.102207402346828,
    1.5135430146223124,
    1.8299512951340673,
    41.67998605315989,
    1.6487049831378497,
    0.019968730667935247,
    1.2241495755484279,
    1.2065702200687627,
    1.0171063118614128,
    0.02392221832280504,
    0.2746651351203456
  ],
  "valid-data-paths": [
    "/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document",
    "/fsx/pilev2/merged/the_stack/the_stack",
    "/fsx/pilev2/merged/pubmed_fix/pubmed_fix",
    "/fsx/pilev2/merged/soda/soda",
    "/fsx/pilev2/merged/uspto/uspto",
    "/fsx/pilev2/merged/pile_of_law/pile_of_law",
    "/fsx/pilev2/merged/free_law_fix/free_law_fix",
    "/fsx/pilev2/merged/amps_fix/amps_fix",
    "/fsx/pilev2/merged/dm_math_fix/dm_math_fix"
  ],
  "valid-data-weights": [2.070006806279234, 1.9171640675752055, 6.43783843754923, 4.586037603579489, 6.954359988235985, 8.001256232179825, 8.49256192461039, 11.102207402346828, 1.5135430146223124, 1.8299512951340673, 41.67998605315989, 1.6487049831378497, 0.019968730667935247, 1.2241495755484279, 1.2065702200687627, 1.0171063118614128, 0.02392221832280504, 0.2746651351203456],
  "test-data-paths": [
    "/fsx/redpajama/redpajama_neox_tokenized/arxiv/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/books/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/c4/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2019/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2020/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2021/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2022/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/common-crawl-by-year/2023/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/stackexchange/tokenized_text_document",
    "/fsx/redpajama/redpajama_neox_tokenized/wiki/tokenized_text_document",
    "/fsx/pilev2/merged/the_stack/the_stack",
    "/fsx/pilev2/merged/pubmed_fix/pubmed_fix",
    "/fsx/pilev2/merged/soda/soda",
    "/fsx/pilev2/merged/uspto/uspto",
    "/fsx/pilev2/merged/pile_of_law/pile_of_law",
    "/fsx/pilev2/merged/free_law_fix/free_law_fix",
    "/fsx/pilev2/merged/amps_fix/amps_fix",
    "/fsx/pilev2/merged/dm_math_fix/dm_math_fix"
  ],
  "test-data-weights": [2.070006806279234, 1.9171640675752055, 6.43783843754923, 4.586037603579489, 6.954359988235985, 8.001256232179825, 8.49256192461039, 11.102207402346828, 1.5135430146223124, 1.8299512951340673, 41.67998605315989, 1.6487049831378497, 0.019968730667935247, 1.2241495755484279, 1.2065702200687627, 1.0171063118614128, 0.02392221832280504, 0.2746651351203456],

  # tokenizer settings
  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/fsx/pile/20B_tokenizer.json",

  # log settings
  "log-interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  "use_wandb": true,
  "wandb_host": "https://stability.wandb.io",
  "wandb_team": "stability-llm",
  "wandb_project": "stable-lm",
  "wandb_group": "1B",
  "wandb_name": "1B.neox.hq",
  # "wandb_id": "",
  # "wandb_resume": "must",

  # multi-node launcher
  "launcher": "slurm",
  "deepspeed_slurm": true
}